### PR TITLE
Various fixes in README files

### PR DESCRIPTION
**Pull request by raphinesse**
The commit messages and the diffs should explain everything.

### CODE REVIEW

**Comment by dpogue** [comment]
I think I agree with you that the ConfigParser readme should probably just be deleted

**Comment by raphinesse** [comment]
@dpogue Should I amend the second commit to remove the `ConfigParser` README instead?

**Comment by dpogue** [comment]
@raphinesse I think that's the best option, yeah

**Comment by raphinesse** [comment]
Done

**Pull request merged**
