### PR TITLE
[WIP] [MAJOR] Remove q from ActionStack.js & PluginManager.js

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

All

### Motivation and Context

It is desired to remove use of `q` as much as possible, as discussed in apache/cordova#7.

I think this is especially true if we apply some test improvements that seem to be needed to pass on jasmine@latest, as proposed in PR #74.

### Description

See title: remove use of `q` from the following modules:

- `src/ActionStack.js`
- `src/PluginManager.js`

I had to exclude a test since it is broken by the proposed changes, with a TODO comment. The same test would also need to be updated to work with jasmine@latest, as discussed and proposed in PR #74.

At this point I think it would be better to remove use of `superspawn` from downstream packages (apache/cordova#16) than try to fix `superspawn` to stop using `q`. I _did_ explain this in apache/cordova#7.

Moving forward:

_Note that this proposal is now marked as MAJOR. I think we should try to get this into the next major release, if possible. Here are some things I think we should watch out for:_
  - As discussed in apache/cordova#7, it is desired to remove `q` usage from the dependent packages first in order to avoid some potential for breaking downstream packages (at this point only the Cordova platform packages are left).
  - It may be desired to completely drop `q` in one shot, maybe after we get rid of `superspawn` or maybe if we decide to fix `superspawn` to stop using `q`.
  - _This change should be considered breaking, for a major release, as discussed below._

### Testing

- [x] `npm test` succeeds in my workarea
- [x] test build on AppVeyor & Travis CI succeed on my own fork
- [ ] check that test build succeeds for Apache Cordova on AppVeyor CI
- [ ] check that test build succeeds for Apache Cordova on Travis CI

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~

### CODE REVIEW

**Comment by dpogue** [comment]
Do these change the returned objects from Q promises to native promises? If yes, then this has to wait until the next major (since Q promises have different methods available than native promises).

**Comment by brodybits** [comment]
> Do these change the returned objects from Q promises to native promises?

Yes

> this has to wait until the next major

Agreed. I just marked this as MAJOR in the title and updated the description.

I would now favor getting this change into the next major release, if possible, to avoid having to maintain the old behavior any longer than is necessary.

Thanks @dpogue for the quick feedback.

**Comment by erisu** [comment]
@brodybits I noticed you 👍 on a review comment to my next major draft branch.

Background: I been working on the next major draft branches for all tooling. It has a lot of changes but each commit will become its own PR. It is all for preparing the next major but as well I been testing CLI 10 already with the currently released platforms (backward compatibility testing).

The commit I was referring too, that you 👍 on, is: https://github.com/apache/cordova-common/commit/6969c666ded7351091dd4a910bfa965d4f6b4e6a

That commit and this PR are basically identical with some slight differences.

We can either drop my commit for your PR or vice versa.

If we decide to use this PR can you update?
1. Fix the merge conflict.
2. Compare my commit with your and ideally try to make sure they are identical. (a reason below)

There were some changes you made that I feel could be done differently. For example, you changed `fin` to `then` but preferably to `finally`. I know the CI might show failures for older node with this recommendation but for next major release, those would not be tested and support dropped so the change is OK. This was just one example that I could remember off hand.

**Comment by brodybits** [comment]
I don't have much time to look at it in the near future, leaving it up to
you now. Sounds like you have a good handle on what is going on here.
Thanks!

**Comment by brodybits** [comment]
Closing in favor of PR #99

**Pull request closed without merging**
