### PR TITLE
3.1.x branch updates from master

### PR DESCRIPTION
**Pull request by brodybits**
I am including some test & documentation updates from master in the `3.1.x` branch, raising this PR just for the record.

### CODE REVIEW

**Comment by janpio** [comment]
Uh why? Is there a planned 3.1.x release?

**Comment by brodybits** [comment]
No, we can probably remove the 3.1.x branch. I guess this kind of branch is only needed if we make a major release.

**Comment by janpio** [comment]
I think it is actually only needed if we actually create a (patch or minor) release after `master` already contains commits that should not be part of that release - everything else is busywork.

**Comment by brodybits** [comment]
Thanks @janpio. I removed the branch since it seems not necessary and I would like to avoid potential confusion. I suspect there should never be a need for older patch branch anyway.

**Pull request merged**
