### PR TITLE
CB-14064: Dependency updates & drop node4 CI

### PR DESCRIPTION
**Pull request by dpogue**
Also added the pull request issue template (copied from cordova-lib) since I noticed that was missing

### CODE REVIEW

**Comment by raphinesse** [comment]
@dpogue The update of `shelljs` breaks the AppVeyor build on Windows. `shell.which('ls')` seems to return something unexpected [here](https://github.com/apache/cordova-common/blob/master/src/superspawn.js#L38).

**Comment by dpogue** [comment]
Yeah, I'm going to get a Windows VM set up to run the tests locally on Windows and see what's going on. I'd really like to not to be stuck on an old version of shelljs :\

**Comment by raphinesse** [comment]
I got a dual boot setup here, let me take a quick look at it.

**Comment by raphinesse** [comment]
Well basically, `shelljs` returns [`ShellString`](https://github.com/shelljs/shelljs#shellstringstr) instances, while `pathname.extname`  expects a plain string. This behavior is not Windows specific either. It's just that the problematic code in `superspawn.js` only is active on Windows.

So we only need to unwrap the encapsulated string. If I replace [the line I linked above](https://github.com/apache/cordova-common/blob/master/src/superspawn.js#L38) with the following, all tests pass on my Windows installation using node 8:
```js
cmd = String(shell.which(cmd) || cmd);
```

**Pull request merged**
