### PR TITLE
CB-14108: fix incorrect count in config_munge in ios.json and android.json

### PR DESCRIPTION
**Pull request by knight9999**
### Platforms affected

All Platforms

### What does this PR do?

This PR affects the cordova prepare command as follows.
1. Check the confliction of config-file tag in config.xml.
2. Prevent unexpected increasing count in config_munge in platformJson (ios/ios.json or android/android.json).
3. Removing unnecessary config_munge directive in platformJson after removing config-file tag.

Futrher, adding related test codes. (ConfigError.spec.js, ConfigChanges.spec.js)

### What testing has been done on this change?

Before this PR,  if we use config.file like

```
   <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <config-file parent="NSCameraUsageDescription" target="*-Info.plist">
            <string>Please permit Camera!</string>
        </config-file>
    </platform>
```
, then `cordova prepare` makes platforms/ios/ios.json 
```
 "config_munge": {
    "files": {
      "*-Info.plist": {
        "parents": {
          "NSCameraUsageDescription": [
            {
              "xml": "<string>Please permit Camera!</string>",
              "count": 1
            }
          ]
        }
      }
    }
  },
```
note that count is 1. Again doing `cordova prepare` makes platforms/ios/ios.json
```
 "config_munge": {
    "files": {
      "*-Info.plist": {
        "parents": {
          "NSCameraUsageDescription": [
            {
              "xml": "<string>Please permit Camera!</string>",
              "count": 2
            }
          ]
        }
      }
    }
  },
```
where the count is 2.
Further if we remove config-file tag in config.xml, `cordova prepare` does not remove anything from  platforms/ios/ios.json.

This unnatural behavior is fixed by this PR.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by dpogue** [comment]
Thanks for the pull request!

I'm not especially familiar with the config munging code, but I know it has been a source of edge case bugs and particular around multiple plugin.xml/config.xml wanting to make conflicting changes. There are a few open issues in JIRA ([CB-13474](https://issues.apache.org/jira/browse/CB-13474), [CB-13486](https://issues.apache.org/jira/browse/CB-13486), and [CB-13514](https://issues.apache.org/jira/browse/CB-13514) in particular) related to those edge cases, and I wanted to check if you thought your changes will have any impact (positive or negative) on those.

**Comment by knight9999** [comment]
Thanks, @dpogue. I try to check the issues CB-13474, CB-13486 and CB-13514.

**Comment by knight9999** [comment]
Sorry, CB-13474, CB-13486 and CB-13514 are the issues in which multiple config-files and/or edit-configs compete each other.  (I.e. xml conflicting)
However my PR does not resolve this kind of conflicting. 
This PR is removing previous config-file settings and applying the new config-file settings correctly.

**Comment by janpio** [comment]
@knight9999 Could you please summarize your changes in the PR title? Thanks.

**Comment by knight9999** [comment]
@janpio I see. I have updated the title.

**Comment by dpogue** [comment]
@knight9999 The changes here (specifically around `unusedConfigMunge `) seem to be causing config-file and edit-config directives in the project config.xml to be skipped sometimes: https://github.com/apache/cordova-android/issues/704

**Comment by ekrapfl** [comment]
@knight9999 and @dpogue
Is anyone looking into this?  It is a pretty major issue that is preventing us from using Cordova 9, which means we are stuck using the horribly slow prepare in Cordova 8.  This appears to be the only thing preventing us from cutting 10+ minutes off of our build times.  Any assistance would be appreciated.  I would love to help, but I don't have the slightest clue what is going on in this commit, so I don't think I am qualified :)

**Comment by dpogue** [comment]
No update from me, I have absolutely no time to work on Cordova stuff these days.

**Pull request merged**
