### PR TITLE
CB-13145: tests for getFramework

### PR DESCRIPTION
**Pull request by audreyso**
tests for getFramework/ get framework tag

### CODE REVIEW

**Comment by stevengill** [comment]
Merged in. Can you close this PR

**Comment by stevengill** [comment]
I think it got merged already. Can you confirm. I think I just forgot to add the commit that auto closes this pr

**Comment by stevengill** [comment]
just close this pr if it is merged :)

**Comment by audreyso** [comment]
@stevengill Hmm I see that this PR has been merged in —> https://github.com/apache/cordova-common/pull/4/files but this one (#6) has not. I don't see these changes from #6 in on master. Both of these PRs have the same issue # though. Should we merge this one in too?

**Comment by stevengill** [comment]
Your right. Merge it in :). Maybe run some manual tests adding and removing a framework to confirm it works before merging

**Pull request merged**
