### PR TITLE
[CB-14145] npm audit in CI TEST WIP - DO NOT MERGE

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

All

### What does this PR do?

- `npm audit` in Travis CI

FUTURE TBD:
- `npm audit` in AppVeyor CI

NOTE: This is a TEST WIP PR, based on _`2.1.x`_, expected to fail with `npm audit` issue. This change is intended to be included in 2.2.x _(for patch release)_ and master for next major release, to verify that any `npm audit` issues would be spotted and resolved in the future.

### What testing has been done on this change?

Check CI results from this PR

### Checklist
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by raphinesse** [comment]
Great idea :+1:

I see one problem though. Builds might be broken by a PR that is not responsible for it. Just because a new security issue has been discovered in the meantime. So maybe we actually want something that pushes us for any issues. Greenkeeper, David DM or maybe auditing in our nightly builds.

**Comment by brodybits** [comment]
> Greenkeeper, David DM or maybe auditing in our nightly builds.

+1 (+100)

I can take a look sometime next month, wouldn't mind if someone can look into these options more quickly.

While I would agree with the concern that CI build may be broken by a PR that is not responsible for it, I would personally favor the idea that we resolve any `npm audit` issues before reviewing and integrating any other changes in the future.

**Comment by raphinesse** [comment]
https://blog.github.com/2017-11-16-introducing-security-alerts-on-github/

**Comment by brodybits** [comment]
> Having these vulnerabilities in cordova-android of course. Any plan to fix this? :)

Yes I am waiting for a review of apache/cordova-android#451.

Also keep in mind that the `npm audit` issues would only affect developer command-line tooling, not expected to affect any published apps. But better to be on the safe side, I think.

Closing now.

**Pull request closed without merging**
