### PR TITLE
feat: setting config.xml value with environment variable

### PR DESCRIPTION
**Pull request by duanju**
It is an useful feature that setting the config.xml values with environment
variables in compile time. This change makes it is possimble to set bellow
config.xml values:

1. packageName
2. android_packageName
3. android_activityName
4. ios_CFBundleIdentifier
5. name
6. shortName
7. description
8. version
9. windows_packageVersion
10. android_versionCode
11. ios_CFBundleVersion
12. author
13. getGlobalPreference
14. getPlatformPreference
15. getPreference

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by breautek** [comment]
Thank you for your contribution.

I fail to understand how it is valuable to have most of these settings as an environment variable because most of these settings would only apply to a single project.

For example... it would be weird to have multiple projects with the same name or bundle id. And you wouldn't be able to update one app version without updating another app that you may be managing on your workstation.

Can you elaborate and point out anything I might be missing? Thanks.

**Comment by duanju** [comment]
Actually, There are some cases that we need to change metadata of app based on build system and environment variables. It is useful and sometimes required. I list some scenarios in my project for the example: 

1. We create app version number by the environment variable CI_JOB_ID which is created by gitlab CI system;
2. We need update app name and icon by different environments in compile time. For example, for my one environment called 'DTMK' , i need change app name as 'DTMK-my-app-name';
3. Some security key or ids also need to be updated in compile time by different environments.

I googled and noticed there are persons achieved that by creating a temp_config file and copy it in hooks to replace config.xml, but i think that let the cordova-common lib to support the feature is more directly so this is why my commit.

**Comment by breautek** [comment]
> I googled and noticed there are persons achieved that by creating a temp_config file and copy it in hooks to replace config.xml

This would actually be far more safer, in my opinion. Both from the usability standpoint and a maintainability standpoint.

Your CI should be able to provide a templated `config.xml` file depending on the project variant that you're building. I think this is far more safer than providing these values from environmental variables where it will be very easy for them to leak into other projects, especially in non-CI environments.

I think I understand where you're coming from but I'm concerned about how people will misuse this feature and report issues because of their improper configuration. which will be hard to reproduce because it is harder to replicate an environment, as opposed to simply sharing their `config.xml` file.

I understand that in your use case is in a CI build, but I don't think it's right to add a feature that can only really be used for CI builds, and have a high risk of causing breakage and confusion outside of a CI build. I wouldn't have much of a concern if these environment variables actually made sense to be applied to multiple projects, but that's not the case here. Most, if not all of the environment variables you're planning to add only applies to a specific project.

Please think about this in a perspective of building a [framework](https://softwareengineering.stackexchange.com/a/133177/259686), then let me know what you think. If you still have an opposing opinion, then that's okay. I'll try to get some feedback from other contributors so that we can figure out the best way forward.

**Comment by dpogue** [comment]
I will again plug my [seymour](https://www.npmjs.com/package/seymour) tool, which was created specifically for changing things like app IDs and version numbers in a CI build process using environment variables.

I feel pretty strongly that this sort of support does not belong directly in Cordova, because as a first-class feature it would introduce too many edge cases around changing variables between builds or handling missing values. That would be a significant increase to the scope of Cordova and make it much harder to maintain.

**Comment by duanju** [comment]
Thank both. I agree with your opinion. Closed this pull request.

**Pull request closed without merging**
