### PR TITLE
CB-13471 : added unit test for config file provider

### PR DESCRIPTION
**Pull request by audreyso**

### CODE REVIEW

**Comment by stevengill** [comment]
Need to see why this is failing on appveyor

**Comment by raphinesse** [comment]
@stevengill @audreyso 

The condition in [this line](https://github.com/apache/cordova-common/blob/master/src/ConfigChanges/ConfigFile.js#L198) has to be changed to work on Windows, since file will be `res\xml` (mind the backslash). Changing the condition to the following fixes it:
```js
file.includes(path.join('res', 'xml'))
```

However, we still need to extend the test itself. It could be that someone uses the following on a Windows machine:
```js
configFile.resolveConfigFilePath('project_dir', 'android', 'res/xml'))
```
Then we would fail again. Thus, we have to normalize the given path right at the start of `configFile.resolveConfigFilePath`:
```js
file = path.normalize(file);
```

These two changes taken together will make the following test (and all others) pass on Windows:
```js
it('resolveConfigFilePath should return file path', function () {
    [path.join('res', 'xml'), 'res/xml'].forEach(function (file) {
        var configPath = path.join('project_dir', 'app', 'src', 'main', file, 'xml');
        expect(configFile.resolveConfigFilePath('project_dir', 'android', file)).toBe(configPath);
    });
});
```

**Comment by dpogue** [comment]
Thanks @raphinesse! I've added a commit (attributed to you) with those changes, and fingers crossed for passing CI

**Comment by raphinesse** [comment]
Thanks for adding the commit and responding so quickly, @dpogue!

**Pull request merged**
