### PR TITLE
Cb 11968 - Add support for config-file in config.xml

### PR DESCRIPTION
**Pull request by matrosov-nikita**
cordova-windows changes: https://github.com/apache/cordova-windows/pull/235

### CODE REVIEW

**Comment by filmaj** [comment]
This LGTM but I will defer to @stevengill as he filed the original issue and is more familiar with it.

**Comment by filmaj** [comment]
@matrosov-nikita can you actually rebase w/ latest master, I just added code coverage reporting to this repo. I just want to get a sense of if we're heading in the right direction.

**Comment by matrosov-nikita** [comment]
@filmaj, done.

**Comment by filmaj** [comment]
Ping @stevengill - this blocks apache/cordova-windows#235

**Comment by stevengill** [comment]
This LGTM. Thanks for implementing this one!

**Comment by brodybits** [comment]
Adding links:
- <https://issues.apache.org/jira/browse/CB-11968> - original report
- <https://github.com/apache/cordova-windows/pull/235>

**Pull request closed without merging**
